In [12]:
def test():
    print('test() for function')
    return
test()

test() for function


In [10]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj=Demo()  #object creation
obj.test()  #call for the method

test() for the class and method


In [17]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
print(p1.fact(6)) 

720


In [18]:
class Demo2:
    def accept(self,p1,p2):
        self.p1=p1
        self.p2=p2
        return
    def Display(self)
    print("p1= "p1)
    print("p2= "p2)

SyntaxError: invalid syntax (<ipython-input-18-b62dba52205a>, line 6)

In [27]:
class Demo2:
    def _init_(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(s):
        return s.p1 + s.p2
c1= Demo2()
print(c1._init_(100,200))
c1.add()

None


300

In [13]:
# Some inheritance
class Person(object):
    #constructor
    def __init__(self,name):
        self.name = name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
#Derived class
class Employee(Person):
    def isEmployee(self):
        return True
emp=Person("Sushma")
print(emp.getName(),emp.isEmployee())
emp1=Employee("Sushma")
print(emp1.getName(),emp1.isEmployee())

Sushma False
Sushma True


In [16]:
import numpy as np
lst=[1.0,2,3,4]
array=np.array(lst)
print(array)
print(array.shape)
print(array.dtype)

[1. 2. 3. 4.]
(4,)
float64


In [18]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [20]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [10]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [11]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column: ",a1[:,1])

slicing column:  [2 5]


In [12]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row: ",a1[:,1])

second row:  [2 5]


In [17]:
a1=np.array([(1,2,3),(8,9,6)])
print("slicing last column: ",a1[:,1])

slicing last column:  [2 9]


In [14]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row: ",a1[1][1])

second row:  5


In [15]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [16]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row: ",a1[0])

first row:  [1 2 3]


In [23]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value=",np.min(a1))
print("max value=",np.max(a1))
print("mean value=",np.mean(a1))
print("median value=",np.median(a1))

[3.55525405 4.65419227 5.90791005 5.63969569 4.08744792 5.21232427
 5.12750801 4.3590035  4.12116954 5.05378423]
min value= 3.5552540479619132
max value= 5.907910050929812
mean value= 4.771828953375454
median value= 4.853988250545916


In [24]:
# Multiply of 1D arrays
#numpy.dot(x,y)--
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [25]:
c1=np.array([(1,2),(3,6)])
c2=np.array([(4,5),(7,8)])
np.dot(c1,c2)

array([[18, 21],
       [54, 63]])

In [29]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

In [32]:
import pandas as pd

In [35]:
dict={"Name":["sushma","yash","danita","mrudula"],
      "Email":["sushma@gmail.com","yash@gmail.com","danita@gmail.com","mrudula@gmail.com"],
      "mobile num":["89798","45876","56697","687676"],
      "address":["hyd","hyd","hyd","hyd"]}
b=pd.DataFrame(dict)
print(b)

      Name              Email mobile num address
0   sushma   sushma@gmail.com      89798     hyd
1     yash     yash@gmail.com      45876     hyd
2   danita   danita@gmail.com      56697     hyd
3  mrudula  mrudula@gmail.com     687676     hyd


In [38]:
b.index=["01","02","03","04"]
print(b)

       Name              Email mobile num address
01   sushma   sushma@gmail.com      89798     hyd
02     yash     yash@gmail.com      45876     hyd
03   danita   danita@gmail.com      56697     hyd
04  mrudula  mrudula@gmail.com     687676     hyd


In [40]:
import pandas as pd
products=pd.read_csv('file1.txt')
print(products)


    test 0 LINE
0   test 1 line
1   test 2 line
2   test 3 line
3   test 4 line
4   test 5 line
5   test 6 line
6   test 7 line
7   test 8 line
8   test 9 line
9    new line 1
10   new line 2
11   new line 1
12   new line 2
13   new line 1
14   new line 2
